# Generated by Django 5.2.7 on 2025-11-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('banks', '0001_initial'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
                model_name='bankdatesrequest',
                name='form_type',
                field=models.ForeignKey(
                        help_text='FK -> FormType',
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        to='indicators.formtype',
                ),
        ),
        migrations.AlterUniqueTogether(
                name='bankdatesrequest',
                unique_together={('bank', 'form_type')},
        ),
    ]
