# Generated by Django 5.2.7 on 2025-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_auto_20251121_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdatesresponse',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, help_text='sha256 хэш представления datetimes', max_length=64, null=True),
        ),
    ]
