# Generated by Django 5.2.7 on 2025-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_bankdatesresponse_data_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(db_index=True, help_text='Полное наименование кредитной организации. Уникально в справочнике.'),
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('name', 'reg_number')},
        ),
    ]
