# Generated by Django 5.2.7 on 2025-11-21 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('csv', 'CSV'), ('pdf', 'PDF'), ('png', 'PNG image')], default='xlsx', help_text='тип результирующего файла', max_length=5)),
                ('file_path', models.FileField(blank=True, help_text='Файл экспорта (S3 URL)', null=True, upload_to='exports/export_files/%Y/%m/%d/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_type', models.ForeignKey(help_text='FK -> FormType, nullable для общих/непривязанных данных', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.formtype')),
                ('user', models.ForeignKey(help_text='FK -> User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
