# Generated by Django 5.2.7 on 2025-11-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(db_index=True, help_text='Регистрационный номер банка в базе ЦБ (рег. номер). Уникальный строковый идентификатор, например "1481".', unique=True)),
                ('bic', models.CharField(help_text='БИК (Bank Identification Code) — банковский идентификатор. Пример: "044525225".')),
                ('name', models.CharField(db_index=True, help_text='Полное наименование кредитной организации. Уникально в справочнике.', unique=True)),
                ('internal_code', models.CharField(help_text='Внутренний код/идентификатор банка в источнике данных (если доступен).')),
                ('registration_date', models.DateTimeField(help_text='Дата регистрации организации (ISO-8601). Может содержать информацию о времени и часовом поясе.')),
                ('region_code', models.CharField(help_text='Код региона (региональный номер/код). Используется для региональных срезов и агрегатов.')),
                ('tax_id', models.CharField(db_index=True, help_text='Идентификатор налогоплательщика (ИНН) или другой налоговый идентификатор. Уникален для организации.', unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Код/название формы отчётности (например "F101", "F123").', unique=True)),
                ('description', models.TextField(help_text='Подробное описание формы: структура, используемые поля, примечания по парсингу и версиям схемы.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BankDatesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(help_text='Регистрационный номер банка в базе ЦБ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(help_text='FK -> Bank', on_delete=django.db.models.deletion.CASCADE, related_name='dates_requests', to='indicators.bank')),
                ('form_type', models.ForeignKey(help_text='FK -> FormType', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.formtype')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BankDatesResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimes', models.JSONField(help_text='Список доступных дат')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(help_text='Ответ', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='indicators.bankdatesrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BankIndicatorDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(help_text='Регистрационный номер банка в базе ЦБ')),
                ('ind_code', models.CharField(help_text='Код индикатора')),
                ('date_from', models.DateTimeField(help_text='Дата с', null=True)),
                ('date_to', models.DateTimeField(help_text='Дата по', null=True)),
                ('dt', models.DateTimeField(help_text='Целевая дата', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(help_text='FK -> Bank', on_delete=django.db.models.deletion.CASCADE, related_name='indicator_data_requests', to='indicators.bank')),
                ('form_type', models.ForeignKey(help_text='FK -> FormType', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.formtype')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BankIndicatorDataResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_indicator_data', models.JSONField(help_text='Список данных индикатора')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(help_text='Ответ', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='indicators.bankindicatordatarequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BankIndicatorsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(help_text='Регистрационный номер банка в базе ЦБ')),
                ('dt', models.DateTimeField(help_text='Целевая дата')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(help_text='FK -> Bank', on_delete=django.db.models.deletion.CASCADE, related_name='indicators_requests', to='indicators.bank')),
                ('form_type', models.ForeignKey(help_text='FK -> FormType', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.formtype')),
            ],
        ),
        migrations.CreateModel(
            name='BankIndicatorsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicators', models.JSONField(help_text='Список индикаторов')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(help_text='Ответ', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='indicators.bankindicatorsrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
