# Generated by Django 5.2.7 on 2025-11-21 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankIndicatorDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(help_text='Регистрационный номер банка в базе ЦБ')),
                ('ind_code', models.CharField(help_text='Код индикатора', null=True)),
                ('date_from', models.DateTimeField(help_text='Дата с', null=True)),
                ('date_to', models.DateTimeField(help_text='Дата по', null=True)),
                ('dt', models.DateTimeField(help_text='Целевая дата', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(help_text='FK -> Bank', on_delete=django.db.models.deletion.CASCADE, related_name='indicator_data_requests', to='banks.bank')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BankIndicatorDataResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_indicator_data', models.JSONField(help_text='Список данных индикатора')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(help_text='Ответ', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='indicators.bankindicatordatarequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BankIndicatorsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(help_text='Регистрационный номер банка в базе ЦБ')),
                ('dt', models.DateTimeField(help_text='Целевая дата')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(help_text='FK -> Bank', on_delete=django.db.models.deletion.CASCADE, related_name='indicators_requests', to='banks.bank')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BankIndicatorsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicators', models.JSONField(help_text='Список индикаторов')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(help_text='Ответ', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='indicators.bankindicatorsrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Код/название формы отчётности (например "F101", "F123").', unique=True)),
                ('description', models.TextField(help_text='Подробное описание формы: структура, используемые поля, примечания по парсингу и версиям схемы.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('title', 'description')},
            },
        ),
        migrations.AddField(
            model_name='bankindicatorsrequest',
            name='form_type',
            field=models.ForeignKey(help_text='FK -> FormType', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.formtype'),
        ),
        migrations.AddField(
            model_name='bankindicatordatarequest',
            name='form_type',
            field=models.ForeignKey(help_text='FK -> FormType', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.formtype'),
        ),
        migrations.AlterUniqueTogether(
            name='bankindicatorsrequest',
            unique_together={('bank', 'form_type', 'reg_number', 'dt')},
        ),
        migrations.AlterUniqueTogether(
            name='bankindicatordatarequest',
            unique_together={('bank', 'form_type', 'reg_number', 'ind_code', 'date_from', 'date_to', 'dt')},
        ),
    ]
