# Generated by Django 5.2.7 on 2025-11-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankindicatorsrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='bankdatesrequest',
            unique_together={('bank', 'form_type')},
        ),
        migrations.AlterUniqueTogether(
            name='bankdatesresponse',
            unique_together={('request', 'datetimes')},
        ),
        migrations.AlterUniqueTogether(
            name='bankindicatordatarequest',
            unique_together={('bank', 'form_type', 'reg_number', 'ind_code', 'date_from', 'date_to', 'dt')},
        ),
        migrations.AlterUniqueTogether(
            name='bankindicatordataresponse',
            unique_together={('request', 'bank_indicator_data')},
        ),
        migrations.AlterUniqueTogether(
            name='bankindicatorsrequest',
            unique_together={('bank', 'form_type', 'reg_number', 'dt')},
        ),
        migrations.AlterUniqueTogether(
            name='bankindicatorsresponse',
            unique_together={('request', 'indicators')},
        ),
        migrations.AlterUniqueTogether(
            name='formtype',
            unique_together={('title', 'description')},
        ),
    ]
