# Generated by Django 5.2.7 on 2025-11-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankindicatordataresponse',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, help_text='sha256 хэш представления bank_indicator_data', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bankindicatorsresponse',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, help_text='sha256 хэш представления indicators', max_length=64, null=True),
        ),
    ]
