# Generated by Django 5.2.7 on 2025-11-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_bankindicatorsrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankindicatordatarequest',
            name='ind_code',
            field=models.CharField(help_text='Код индикатора', null=True),
        ),
    ]
