# Generated by Django 5.2.7 on 2025-11-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_alter_bankindicatordatarequest_ind_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankdatesresponse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bankindicatordataresponse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bankindicatorsresponse',
            unique_together=set(),
        ),
    ]
