"""
Django settings for bank_iq project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
from environs import Env


env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'test-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', True)

ALLOWED_HOSTS = [h.strip() for h in
                 os.getenv('DJANGO_ALLOWED_HOSTS', default='127.0.0.1,localhost,0.0.0.0,backend').split(',')
                 if h.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'drf_spectacular',
    'storages',
    'rest_framework_simplejwt.token_blacklist',

    'core',
    'reports.apps.ReportsConfig',
    'indicators.apps.IndicatorsConfig',
    'exports.apps.ExportsConfig',
    'banks.apps.BanksConfig',
    'accounts.apps.AccountsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bank_iq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bank_iq.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL', f'postgres://postgres:1234@db:5432/bankiq')
try:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
except Exception:
    DATABASES = {
        'default': dj_database_url.parse(f'sqlite:///{BASE_DIR / "db.sqlite3"}')
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework_simplejwt.authentication.JWTAuthentication', ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny', ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    'ALGORITHM': 'HS256',

    "AUTH_HEADER_TYPES": ("Bearer",),
    "UPDATE_LAST_LOGIN": True,
}

# Настройки для drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'User Management API',  # Название API
    'DESCRIPTION': 'API сервиса BankIQ',  # Описание API
    'VERSION': '1.0.0',  # Версия API
    'SERVE_INCLUDE_SCHEMA': False,  # Отключение схемы в ответах API,
    'SCHEMA_PATH_PREFIX': r'/api/',

    'COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    'SECURITY_REQUIREMENTS': None,
    'COMPONENT_SPLIT_REQUEST': True,
}

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BROKER", "redis://redis:6379/0")

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_S3_ENDPOINT_URL = os.environ.get("MINIO_ENDPOINT", "http://127.0.0.1:9000")
AWS_ACCESS_KEY_ID = os.environ.get("MINIO_ACCESS_KEY", "minio-access-key")
AWS_SECRET_ACCESS_KEY = os.environ.get("MINIO_SECRET_KEY", "minio-secret-key")
AWS_STORAGE_BUCKET_NAME = os.environ.get("MINIO_BUCKET", "bankiq-media")

AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_SECURE = os.getenv("MINIO_SECURE", "0") != "0"
AWS_S3_USE_SSL = None  # "public-read" (все могут читать)
AWS_QUERYSTRING_AUTH = True  # если хотите публичные URL (без подписей)
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = 'private'

STATIC_URL = "/static/"

if AWS_S3_ENDPOINT_URL:
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"
else:
    MEDIA_URL = "/media/"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # важно — не отключать логи Django и библиотек
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(levelname)-8s %(name)s:%(lineno)d %(message)s"
        },
        "simple": {
            "format": "%(levelname)-8s %(name)s: %(message)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        # Логи Django (для избегания громоздких debug-логов можно поставить INFO)
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Приложение — подставить корневой модуль проекта или другой модуль
        "bank_iq": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Подключим библиотеки (опционально) чтобы видеть ошибки s3/boto3
        "botocore": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "boto3": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "storages": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}
