# Generated by Django 5.2.7 on 2025-11-21 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CbrApiDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('credit', 'Кредитные ставки'), ('deposit', 'Депозитные ставки'), ('params_check', 'Проверка параметров')], db_index=True, help_text='Тип запроса к API ЦБ РФ', max_length=15)),
                ('publication_id', models.IntegerField(db_index=True, help_text='ID публикации в API ЦБ РФ', null=True)),
                ('dataset_id', models.IntegerField(db_index=True, help_text='ID набора данных в API ЦБ РФ', null=True)),
                ('measure_id', models.IntegerField(db_index=True, help_text='ID разреза (measure) в API ЦБ РФ', null=True)),
                ('from_year', models.IntegerField(help_text='Начальный год периода запроса', null=True)),
                ('to_year', models.IntegerField(help_text='Конечный год периода запроса', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['rate_type', 'publication_id', 'dataset_id', 'measure_id', 'from_year', 'to_year'], name='reports_cbr_rate_ty_b0b672_idx'), models.Index(fields=['rate_type', 'publication_id', 'dataset_id', 'measure_id'], name='reports_cbr_rate_ty_c05ad0_idx')],
                'unique_together': {('rate_type', 'publication_id', 'dataset_id', 'measure_id'), ('rate_type', 'publication_id', 'dataset_id', 'measure_id', 'from_year', 'to_year')},
            },
        ),
        migrations.CreateModel(
            name='CbrApiDataResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_data', models.JSONField(help_text='Обработанные и нормализованные данные для аналитики', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(help_text='FK -> CbrApiDataRequest', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reports.cbrapidatarequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
