# Generated by Django 5.2.7 on 2025-11-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_cbrapidatarequest_dataset_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbrapidataresponse',
            name='raw_data',
        ),
    ]
